# Generated by Django 5.2.5 on 2025-08-09 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='emoji',
            field=models.CharField(blank=True, default='📝', max_length=10),
        ),
    ]
